markdown: kramdown
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
exclude:
    - README.md
    - LICENSE.md
    - node_modules
    - gulpfile.js
